### PR TITLE
upgrade to influxdb 1.0.0

### PR DESCRIPTION
**Pull request by tklicki**
Works with current debops roles and official influxdb 1.0.0 Debian package

### CODE REVIEW

**Review by drybjed — COMMENTED** [review]
Changes look good, although I haven't tested them. I wonder if the `influxdb.conf` is marked as a Conffile, and if the original one could be diverted to preserve it...

The role currently does not have a test on Travis, not sure what to do about it. @scibi, do you plan to work on the role? Otherwise I could check this PR when I have some time and perhaps take over the role, unless @ypid has more experience with InfluxDB (I have none).

**Comment by scibi** [comment]
@drybjed thanks for your remarks. I guess @tklicki will be happy to add some tests - Tomek, am I right? ;)
@drybjed is there any document with coding guidelines for DebOps roles? I'm thinking about things like variable names (role_name__some_variable), use of playbooks instead of dependencies in meta or guidelines of writing tests or using tools to generating readme files with `ansigenome`.

**Comment by tklicki** [comment]
Sure! @scibi, @drybjed - I can try to write some tests. Are there any guidelines anywhere or should I use examples from other debops roles? What else can be improved here? I'm listening to your comments @drybjed carefully - I'm quite new to debops but I think it is great project. What should we do to have this role migrated from contrib to main tree?

**Comment by drybjed** [comment]
At the moment there are no guidelines specific to the roles themselves. You should read at least [DebOps Guidelines and Policies](https://docs.debops.org/en/latest/debops-policy/docs/index.html) to be familiar with where the project is heading - any suggestions for improvements are welcome, by the way.

You can look at the [DebOps status page](https://debops.org/status.html) to see what roles are up to our current practices - at the moment Standards Version v0.2.1 is the most current. If you want to look at specific roles, [debops.apt_proxy](https://github.com/debops/ansible-apt_proxy), [debops.dokuwiki](https://github.com/debops/ansible-dokuwiki), [debops.mariadb_server](https://github.com/debops/ansible-mariadb_server) should be a good representative set of "current roles".

For the Travis tests, I think that @ganto might have some idea how to do them for `debops-contrib` roles. He uses [his own repository with tests](https://github.com/debops-contrib/ansible-checkmk_server/blob/master/.travis.yml) which you might consider [checking out](https://github.com/ganto/debops-test-suite). I imagine that when the role is moved to the DebOps organization, the tests will be copied to the DebOps test suite.

I think that you should start by creating a repository for the tests and pointing the InfluxDB role `.travis.yml` file to it, when tests are working you can try updating the role itself.

**Comment by drybjed** [comment]
@tklicki BTW, come over to `#debops` at FreeNode sometime. Yeah, I saw you there, but I was offline at that moment. You should hang out on the channel more. :-)

**Comment by tklicki** [comment]
Thank you - I will do this for sure, just need to remind myself something abour irssi and establish permanent session somewhere ;-) I was just about to ask what is the best place just to talk to other role developers, but you were faster with the answer ;-)

**Comment by drybjed** [comment]
@tklicki There's also [the project mailing list](https://lists.debops.org/mailman/listinfo/debops-users) if you prefer that interface. It's currently not very active, but I wouldn't mind changing that. And it could be helpful for the users that don't frequent the IRC channel to have a browsable archive/history to look at, I imagine. So if you prefer that, go ahead - it's certainly better and more centralized than GitHub issues which are split among multiple repositories.

**Pull request merged**
